### ISSUE TITLE
Flask listen all ip adresses

### ISSUE THREAD

**Issue by ctnkyrd** [kasdevelopment/referans#10]
not only localhost but also listen 192.**

**Comment by ctnkyrd** [comment]
@KenanBolat flask documentation da production için bir sayfa hazırlamışlar: http://flask.pocoo.org/docs/1.0/tutorial/deploy/ 
burada yazanlara göre deployment yapabiliriz

**Comment by KenanBolat** [comment]
Ben deployment için bir sanal makine oluşturdum ve Global olarak erişime açtım. 

- [**`http://185.67.125.34:5000`**](http://185.67.125.34:5000)

- Deploy edebilmek için kullandığım kod aşağıdaki gibidir; 
`while true; do flask run --host=0.0.0.0; done;`

- Kod içerisinde hard coded olarak localhost:<port> yazmadıkça herhangi bir sorun olacağını düşünmüyorum
