### ISSUE TITLE
A simple demo has been requested 

### ISSUE THREAD

**Issue by KenanBolat** [kasdevelopment/referans#9]
A simple demo has been requested to show what will be achieved when the project has been done. 
- [x] Without D3.js simple click and display given two process in hand 
- [x] Instead of web alternative some desktop example can be shown for a quick demo

**Comment by ctnkyrd** [comment]
- data variable a alındı,
- bölge-il-ilçe olarak hiyeraşik olarak dd lere listendi, 
- tabpane eklendi (bölge, il, ilçe)
- district class yazılmaya başlandı.

**Comment by ctnkyrd** [comment]
![image](https://user-images.githubusercontent.com/26214532/58380122-f6ec4c00-7fb5-11e9-890c-557a68c048fe.png)

**Comment by ctnkyrd** [comment]
completed at demo branch
